data = {
    "it": {
        "menu_home": "Home",
        "menu_maker_designer": "Maker e designer",
        "menu_ecommerce": "eCommerce",
        "menu_about_us": "Chi siamo",

        "generic_keep_in_touch_title": "Restiamo connessi",
        "generic_keep_in_touch_label": "A breve saremo online, ti contatteremo solo per offrirti sconti e anticipazioni per ripagare la tua fiducia",
        "generic_keep_in_touch_email_placeholder": "La tua Email",
        "generic_keep_in_touch_btn_send": "INVIA",
        "generic_keep_in_touch_msg": "Grazie per esserti registrato",
        "generic_keep_in_touch_error_msg": "Email è un campo obbligatorio",
        "generic_keep_in_touch_disclaimer": "Il tuo indirizzo di messaggistica è usato solamente per inviarti le nostre lettere informative e le informazioni relative alle attività di Tamatara S.r.l.. Puoi usare il link di disiscrizione integrato nella newsletter in qualsiasi momento.",

        "index_title1": "Diamo valore ad ogni oggetto,<br> creato su misura per te",
        "index_label1": "Semplifichiamo l'acquisto e la vendita di oggetti artigianali, di design ed ecosostenibili",
        "index_title2": "Artigianato, innovazione, made in Italy",
        "index_label2": "Il migliore negozio online dove le idee di designer internazionali trovano il modo di essere realizzate grazie alle abilità artigiane dei migliori makers italiani",
        "index_btn1": "Voglio saperne di più",
        "index_title3": "La nostra mission",
        "index_label3-1": "Mettere in contatto persone che cercano prodotti unici e di qualità con i migliori maker del Made in Italy, ad un prezzo equo, favorendo cosi lo sviluppo dell'artigianato 4.0",
        "index_label3-2": "Valorizziamo i migliori designers internazionali e makers italiani svelando le loro creazioni ed aiutandoli a promuovere il loro business, offrendo tecnologia, user experience, strumenti di marketing e supporto logistico",
        "index_title4": "Creativi, con passione",
        "index_label4": "Ampliamo l'orizzonte dell'oggettistica artgianale semplificando il contatto tra persone",
        "index_designer": "Designer",
        "index_lbl_designer": "Trasformiamo le tue creazioni in oggetti per i nostri clienti, tutelando le tue opere digitali",
        "index_maker": "Maker",
        "index_lbl_maker": "Lavora con la tua passione, crea con la stampante 3D e mostra le tue abilità artigiane",
        "index_client": "Cliente",
        "index_lbl_client": "Uniamo artigianalità, tecnologia e design per creare oggetti unici al momento del tuo acquisto",
        "index_title5": "I migliori artigiani digitali italiani",
        "index_label5": "Per creare con cura ogni oggetto servono i migliori: la nostra rete di artigiani digitali, makers e designers, saranno in grado di realizzare tutto ciò che è pensabile. La rete è in continua espansione, se vuoi <b>lavorare</b> con le tue abilità di <b>stampa 3D</b> e di <b>design</b> sei nel posto giusto",
        "index_btn2": "Espandi il tuo business",
        "index_title6": "Molto più di un eCommerce",
        "index_title7": "Parlano di noi",

        "maker_title1": "Sei un maker e/o un designer?",
        "maker_label1": "Potresti essere tra i primi ad usufruire dei vantaggi di Tamatara",
        "maker_btn1": "Voglio saperne di più",
        "maker_title2": "La tua stampante 3D, le tue abilità artigiane, il nostro aiuto, niente di più",
        "maker_label2": "Offriamo una piattaforma innovativa in grado di proporti a clienti secondo le tue abilità artigiane",
        "maker_maker_title1": "Lavora con noi",
        "maker_maker_label1": "Approfitta dei nostri servizi gratuiti per espandere il tuo business",
        "maker_maker_title2": "Stampa in 3D",
        "maker_maker_label2": "Grazie alle tue stampanti 3D realizzerai oggetti per i nostri clienti",
        "maker_maker_title3": "Tecniche artigiane",
        "maker_maker_label3": "Crediamo nelle tue abilità e nel valore della post-produzione",
        "maker_title3": "Avrai a disposizione tutto quello che ti serve per soddisfare i tuoi clienti",
        "maker_label3-1": "Semplifichiamo il tuo lavoro fornendoti il modello 3D già pronto per la stampa, con dettagli specifici e guide per eventuali lavori di post-produzione. Tu mettici le tue abilità, noi ti portiamo i clienti",
        "maker_label3-2": "La nostra vision è rendere accessibile e semplice l'artigianato digitale. Tamatara nasce come eCommerce per clienti amanti di oggetti artigianali e su misura. Crediamo fortemente che la community di makers italiani sia pronta ad entrare con profitto nel mercato di consumo, supportata da servizi innovativi e formazione su misura",
        "maker_title4": "Designer, sei pronto a guadagnare dalle tue idee?",
        "maker_label4": "I tuoi modelli 3D comporranno il nostro catalogo, i clienti vedranno un oggetto finito con la possibilità di comprarlo come tu lo hai immaginato",
        "maker_designer_title1": "Proponi le tue creazioni",
        "maker_designer_label1": "Sei tu la mente, formiamo artigiani digitali per trasformarle in realtà",
        "maker_designer_title2": "Licenza e copyright",
        "maker_designer_label2": "Proteggiamo i tuoi file con firma digitale e contratti specifici",
        "maker_designer_title3": "Esplora il potenziale",
        "maker_designer_label3": "Lasciati guidare dai nostri servizi gratuiti per diffondere la tua idea",
        "maker_title5": "Tamatara è pensata per rendere la tua idea riproducibile in sicurezza",
        "maker_label5-1": "Saremo la tua vetrina agli occhi del mondo, proteggendo le tue idee e garantendoti che solo i migliori makers avranno accesso ai tuoi modelli 3D per soddisfare i clienti. Un singolo upload, una vetrina infinita e gratuita",
        "maker_label5-2": "Grazie a software specifici e contratti stipulati al momento dell'ordine ci impegnamo a garantire il massimo riserbo per i tuoi modelli 3D. Solo il maker incaricato dal cliente per stampare la tua idea avrà accesso esclusivo al file. Ti basterà caricarlo, inserire le informazioni utili per riprodurlo come tu lo hai pensato e impostare un prezzo per il singolo uso commerciale",
        "maker_title6": "Restiamo in contatto",
        "maker_label6": "A breve lanceremo la beta-test e ci piacerebbe averti a bordo per poterti mostrare in anteprima le potenzialità di Tamatara",
        "maker_form_firstname": "Nome <sup>*</sup>",
        "maker_form_lastname": "Cognome <sup>*</sup>",
        "email": "Email <sup>*</sup>",
        "maker_form_phone": "Numero di telefono",
        "maker_form_ima": "Sono un <sup>*</sup>",
        "maker_form_ima_maker": "Maker",
        "maker_form_ima_designer": "Designer",
        "maker_form_ima_maker_designer": "Maker/Designer",
        "maker_form_category": "Sono specializzato in queste categorie merceologiche <sup>*</sup>",
        "maker_form_category_art": "Arte e oggetti da collezione",
        "maker_form_category_home": "Casa e arredi",
        "maker_form_category_dpi": "Dispositivi (DPI)",
        "maker_form_category_robotics": "Elettronica e robotica",
        "maker_form_category_gadgets": "Gadgets",
        "maker_form_category_games": "Giocattoli e intrattenimento",
        "maker_form_category_jewelery": "Gioielli e accessori",
        "maker_form_category_cosplay": "Miniature e Cosplay",
        "maker_form_category_other": "Altro",
        "maker_form_error_msg": "Riempi i campi obbligatori",

        "client_title1": "Prodotti unici ideati da designers internazionali creati al momento del tuo ordine da artigiani italiani",
        "client_label1": "L'unico negozio online semplice, divertente ed economico in grado di offrirti l'unicità dell'artigianato insieme alle potenzialità della stampa 3D",
        "client_title2": "Immagina le potenzialità della creatività unite alla tecnica e all'ecosostenibilità",
        "client_label2": "Acquistare un oggetto unico sfuttando le abilità degli artigiani digitali italiani non è mai stato cosi semplice",
        "client_block_title1": "Creato per te",
        "client_block_label1": "Ogni oggetto che sceglierai verrà creato al momento grazie alla stampante 3D ed a tecniche artigiane manuali. E si, potrai personalizzarlo",
        "client_block_title2": "Innovare è migliorare",
        "client_block_label2": "Offriamo una vetrina agli artigiani delle nostre città, valorizzandoli. Inoltre la stampante 3D crea oggetti a basso impatto ambientale e con materiali ecosostenibili",
        "client_block_title3": "Semplice",
        "client_block_label3": "Facilitamo il contatto tra creatività, tecnologia e oggettistica di consumo. Acquistare oggetti innovativi non è mai stato cosi semplice",
        "client_title3": "Crediamo che la realizzazione di ogni singolo oggetto sia il valore aggiunto di un acquisto",
        "client_label3-1": "Non più oggettistica in serie, valorizziamo ogni grammo di materiale utilizzato per soddisfare le tue esigenze, aiutando il tuo territorio e la natura",
        "client_label3-2": "In Tamatara troverai un vasto catalogo di oggettistica di design, gadget, modellismo, giocattoli, gioiellistica. Tutto quello che è pensabile è realizzabile grazie alla creatività dei designers e le capacità artigiane e tecniche dei makers. Ogni acquisto aiuterà gli artigiani digitali italiani a rilanciare l'oggettistica made in Italy",

        "team_title1": "Chi siamo",
        "team_label1": "Tamatara nasce per dare lavoro e visibilità agli artigiani digitali. Le nostre competenze si intersecano al meglio per perseguire questa visione",
        "team_title2": "La vision",
        "team_label2": "Siamo una start-up innovativa nel settore dell’eCommerce che sfrutta le potenzialità della stampa 3D e le abilità dei makers italiani per rendere accessibile e sostenbile l'acquisto di prodotti artigianali realizzati al momento. Per fare ciò siamo da sempre guidati da una vision ben precisa:",
        "team_title_vision1": "Creare opportunità lavorative",
        "team_label_vision1": "Il primo concept di Tamatara è nato per formare e dare lavoro a ragazzi universitari. Siamo una vetrina gratuita per tutti i professionisti o appassionati che intendono guadagnare con le loro abilità, favorendo così lo sviluppo dell'ecosistesma dell'artigianato 4.0 italiano.",
        "team_title_vision2": "Innovare l'artigianato",
        "team_label_vision2": "Uniamo l'artigianato Made in Italy con la tecnologia della stampa 3D. Questo permette di creare oggetti unici su misura per il cliente, con materiali innovativi e ecosostenibili, con il minor spreco possibile di materiale e con tutte le potenzialità che il digitale offre.",
        "team_title_vision3": "Facilitare il contatto",
        "team_label_vision3": "La community di artigiani digitali italiani è ricca di talento e di tecnica ma fatica a trovare un linguaggio comune con il consumatore. Tamatara vuole facilitare questa comunicazione ed investire in campagne mirate a diffondere il valore aggiunto di un oggetto che viene realizzato grazie al contatto tra l'idea di un designer internazionale e le abilità di un artigiano digitale italiano.",
        "team_title3": "Il Team",
        "team_label3": "Crediamo fermamente nelle relazioni e nel creare reti positive. Ognuno con le sue capacità umane e professionali porta il valore aggiunto utile a perseguire nella nostra vision. <br>Uniti si cambia, singolarmente si eccelle",

        "team_andrea_desc": "Laureato in sociologia, con esperienze nello sviluppo front-end e nella gestione delle risorse umane. Da sempre appassionato di tecnologia e di come questa possa influire nella psicologia umana e nelle dinamiche sociali.",
        "team_andrea_cit": "“Credo fermamente che innovazione sia sinonimo di relazioni sociali ed uso etico della tecnologia”",
        "team_gabriele_desc": "Laureato in economia aziendale e management alla Bocconi con esperienze in grandi realtà aziendali, appassionato di tecnologia fin da bambino cresce con la visione che le tecnologie possano creare un mondo a misura d’uomo.",
        "team_gabriele_cit": "“Con il talento puoi avere successo, con la dedizione ed il sacrificio puoi superare ogni limite”",
        "team_fabio_desc": "Laureato in business administration e management. Esperienza professionale maturata nel settore dei servizi con una comprovata storia di lavoro nel project management, gestione del brand e sviluppo del business. Appassionato di innovazione, marketing e comunicazione d'impresa in genere, ovunque questo implichi l'utilizzo delle nuove tecnologie.",
        "team_fabio_cit": "“Non si può descrivere la passione, la si può solo vivere”",
        "team_ilario_desc": "Laureato in informatica e con una grande passione per tutto ciò che è tecnologia e innovazione, attraverso gli anni vissuti in aziende  IT, insegue e promuove a 360 gradi le nuove tecnologie e i sistemi di ultima generazione.",
        "team_ilario_cit": "“Nel momento in cui dubiti di poter volare, perdi per sempre la facoltà di farlo”"
    }
}
DEFAULT_LANGUAGE = "it"     # TODO: change to en?


def get_language(lang):
    return data['it']
    # return data.get(lang, data[DEFAULT_LANGUAGE])
